Patch SetLogger Bug: Shared logger among requests creates repeating logging context
xmidt-org/bascule pull request #160
Opened 2022-11-10 19:52 UTC by denopink

What's included:
- #159

2022-11-10 21:57 UTC, johnabass requested changes

2022-11-10 21:57 UTC, johnabass commented on basculehttp/log.go
>  				zap.String("request.method", r.Method),
Picking nits:  this should probably be "request.Method" to match the casing of the other fields.

2022-11-11 01:43 UTC, johnabass approved these changes

2022-11-11 16:09 UTC, renaz6 approved these changes

2022-11-11 18:03 UTC, merged